version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: cd examples/foo_umbrella && mix deps.get
      - run: mix check
